### ISSUE TITLE
Assert when Edit + Move

### ISSUE THREAD

**Issue by studiowildcard** [perforce/p4transfer#12]
We have hit cases where files were moved within the current stream but also edited (seemingly to avoid compilation errors since the files are now in a new location). The steps to replicate this behavior seem to be:

1. Open original file for Edit
2. Move (Mark original file for delete)
3. Make changes to the file (which is now Add / Edit)
4. Submit

In replicating this change, p4transfer asserts:

```
2021-11-05 08:39:34,908:P4Transfer:ERROR:
Traceback (most recent call last):
  File "P4Transfer.py", line 2168, in replicate
    num_changes = self.replicate_changes()
  File "P4Transfer.py", line 1985, in replicate_changes
    targetChange = self.target.replicateChange(fileRevs, srcFileLogs, change, self.source.p4.port)
  File "P4Transfer.py", line 1234, in replicateChange
    self.processChangeRevs(fileRevs, srcFileLogs)
  File "P4Transfer.py", line 1189, in processChangeRevs
    self.replicateIntegration(f)
  File "P4Transfer.py", line 1636, in replicateIntegration
    assert(afterAdd)
AssertionError
```

**Comment by cpiketech** [comment]
Hello, was there ever an update for this issue? It is still occurring and I have witnessed some funky transfers where files are not moved correctly, resulting in move/add(edit) files existing twice. One revision as the previous pre-move file and a second revision as the moved file.
