### ISSUE TITLE
UnicodeDecodeError during transfer of first changelist

### ISSUE THREAD

**Issue by kevin-white-sony** [perforce/p4transfer#16]
I've configured P4Transfer and started the first transfer.  The first changelist generated the following error:
```
2023-01-26 04:01:01,675:P4Transfer:INFO: Logging to file: /home/perforce/log-P4Transfer-20230126040101.log
2023-01-26 04:01:33,885:P4Transfer:INFO: Transferring 1000 changes
2023-01-26 04:01:34,831:P4Transfer:INFO: Syncing 1000 changes
2023-01-26 04:01:34,831:P4Transfer:INFO: Finding change sizes
2023-01-26 04:01:40,991:P4Transfer:INFO: Syncing filerevs 59739, size 2.8 GB
2023-01-26 04:01:41,025:P4Transfer:WARNING: warning result: ['//p4transfer-client/... - file(s) not opened on this client.']
2023-01-26 04:01:41,025:P4Transfer:INFO: Processing change: 102493, files 18887, size 1.1 GB "Rename //<redacted>/... To //<redacted>/..."
2023-01-26 04:01:47,720:P4Transfer:INFO: Synced 1/1000 changes, files 5353/59739 (9.0 %), size 508.6 MB/2.8 GB (17.8 %)
2023-01-26 04:01:47,781:P4Transfer:INFO: Synced 1/1000 changes, files 15879/59739 (26.6 %), size 986.5 MB/2.8 GB (34.6 %)
2023-01-26 04:02:20,480:P4Transfer:ERROR: 'utf-8' codec can't decode byte 0xb5 in position 341: invalid start byte
Traceback (most recent call last):
  File "/perforce/transfer/p4transfer/P4Transfer.py", line 2588, in replicate
    num_changes = self.replicate_changes()
  File "/perforce/transfer/p4transfer/P4Transfer.py", line 2404, in replicate_changes
    fileRevs, specialMoveRevs, srcFileLogs = self.source.getChange(change['change'])
  File "/perforce/transfer/p4transfer/P4Transfer.py", line 1249, in getChange
    chRev.updateDigest()
  File "/perforce/transfer/p4transfer/P4Transfer.py", line 584, in updateDigest
    self.fileSize, self.digest = getKTextDigest(self.fixedLocalFile)
  File "/perforce/transfer/p4transfer/P4Transfer.py", line 479, in getKTextDigest
    contents = contents.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 341: invalid start byte
2023-01-26 04:02:20,481:P4Transfer:INFO: Sleeping on error for 60 minutes
```

What are my next steps in troubleshooting this issue?

**Comment by rcowham** [comment]
What's in the logfile?

**Comment by kevin-white-sony** [comment]
```2023-01-26 04:01:44,718:P4Transfer:DEBUG: src('sync', '//p4transfer-client/...@=102493')
2023-01-26 04:01:47,720:P4Transfer:INFO: Synced 1/1000 changes, files 5353/59739 (9.0 %), size 508.6 MB/2.8 GB (17.8 %)
2023-01-26 04:01:47,781:P4Transfer:INFO: Synced 1/1000 changes, files 15879/59739 (26.6 %), size 986.5 MB/2.8 GB (34.6 %)
2023-01-26 04:02:20,331:P4Transfer:DEBUG: src[]
2023-01-26 04:02:20,480:P4Transfer:ERROR: 'utf-8' codec can't decode byte 0xb5 in position 341: invalid start byte
Traceback (most recent call last):
  File "/perforce/transfer/p4transfer/P4Transfer.py", line 2588, in replicate
    num_changes = self.replicate_changes()
  File "/perforce/transfer/p4transfer/P4Transfer.py", line 2404, in replicate_changes
    fileRevs, specialMoveRevs, srcFileLogs = self.source.getChange(change['change'])
  File "/perforce/transfer/p4transfer/P4Transfer.py", line 1249, in getChange
    chRev.updateDigest()
  File "/perforce/transfer/p4transfer/P4Transfer.py", line 584, in updateDigest
    self.fileSize, self.digest = getKTextDigest(self.fixedLocalFile)
  File "/perforce/transfer/p4transfer/P4Transfer.py", line 479, in getKTextDigest
    contents = contents.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 341: invalid start byte
```

**Comment by rcowham** [comment]
Need to see the log file header - e.g. python version, p4python etc.
You can send it to me privately if you wish: rcowham at <obvious company>.com

**Comment by th3de3th** [comment]
@kevin-white-sony check this thread, it can help you too https://github.com/perforce/p4transfer/issues/5
