### ISSUE TITLE
utf-8 codec error

### ISSUE THREAD

**Issue by harsha436** [perforce/p4transfer#5]
We are seeing below issue with some changes during the migration. We can proceed with the migration by excluding the paths n yaml file but this is the third time we got this error. Any idea what is this about and how to resolve this?

root@dc2-p4-gl-05:/scm/p4transfer # tail -20 log-P4Transfer-20210510090851.log

 'rev': 1,
 'time': datetime.datetime(2017, 7, 25, 7, 14, 59),
 'type': 'text+kx',
 'user': 'amirl'}]}]
2021-05-10 09:16:41,946:P4Transfer:DEBUG: src('sync', '//hmallesh_test_transfer/...@=219564')
2021-05-10 09:16:52,093:P4Transfer:DEBUG: src[]
2021-05-10 09:16:53,552:P4Transfer:ERROR: 'utf-8' codec can't decode byte 0xd1 in position 0: invalid continuation byte
Traceback (most recent call last):
  File "P4Transfer.py", line 2149, in replicate
    num_changes = self.replicate_changes()
  File "P4Transfer.py", line 1965, in replicate_changes
    fileRevs, branchRevs = self.source.getChange(change['change'])
  File "P4Transfer.py", line 1114, in getChange
    chRev.updateDigest()
  File "P4Transfer.py", line 524, in updateDigest
    self.fileSize, self.digest = getKTextDigest(self.fixedLocalFile)
  File "P4Transfer.py", line 425, in getKTextDigest
    contents = contents.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 0: invalid continuation byte
2021-05-10 09:16:53,552:P4Transfer:INFO: Sleeping on error for 60 minutes
root@dc2-p4-gl-05:/scm/p4transfer #

**Comment by th3de3th** [comment]
Got the same issue on the recent version.
Any updates?

**Comment by th3de3th** [comment]
This is solved my issue

```
$ diff -u p4transfer/P4Transfer.py p4transfer/P4Transfer.py.modified.py 
--- p4transfer/P4Transfer.py	2023-09-21 16:31:03.163049658 +0000
+++ p4transfer/P4Transfer.py.modified.py	2023-10-14 21:37:53.996647171 +0000
@@ -516,14 +516,15 @@
 
 def getKTextDigest(fname):
     "Special calculation for ktext files - ignores lines with keywords in them"
+    print ('!!!!FILE!!!! {0}'.format(os.path.abspath(fname)))
     contents = readContents(fname)
     if python3:
-        contents = contents.decode()
+        contents = contents.decode(errors='surrogateescape')
     m = hashlib.md5()
     # Optimisation to search on whole file
     if not re_rcs_keywords.search(contents):
         if python3:
-            m.update(contents.encode())
+            m.update(contents.encode(errors='surrogateescape'))
         else:
             m.update(contents)
         fileSize = os.path.getsize(fname)
@@ -533,7 +534,7 @@
     for line in lines:
         if not re_rcs_keywords.search(line):
             if python3:
-                m.update(line.encode())
+                m.update(line.encode(errors='surrogateescape'))
             else:
                 m.update(line)
             fileSize += len(line)
```

**Comment by th3de3th** [comment]
@rcowham would you mind to comment on that?

**Comment by rcowham** [comment]
Hmmm. Looks OK as a workaround. I wonder if it is better to allow an extra locale setting to be specified?

**Comment by th3de3th** [comment]
Not sure, that it can provide a reliable solution for keeping data consistent while encoding, since we never sure what exact encoding clients are using until it's not aligned for all developers, which is i believe a rare case. Most common, when several teams using their own approach for encoding settings.
However ability to confiigure this would provide at least instruments for administrators to try manage this on their own.

**Comment by th3de3th** [comment]
As well for some cases it could can be a good idea to allow restrict (make it configurable) of processsing text+k at all, this will eliminate such kind of issues at all. I believe some of cases (for some setups) not requires to update values of rcs tags while migration.
